### ISSUE TITLE
Roadmap to 3.0.0

### ISSUE THREAD

**Issue by mrmlnc** [mrmlnc/syncy#41]
## Algorithm

  * [ ] Improve algorithm of comparing directories (fix for #37).

## Options

  * [ ] Divide `updateAndDelete` option to `updateDestFiles` and `deleteDestFiles` (fix #40).

## Common

  * [ ] `syncy-cli` (fix #11).
