### ISSUE TITLE
Roadmap to 2.1.0

### ISSUE THREAD

**Issue by mrmlnc** [mrmlnc/syncy#8]
- [x] Use TypeScript
- [x] Add DTS file
- [x] Use Async/Await for `mkdirp` and file search
- [x] [performance experiment] Try to replace `readdir-enchanted` + `micromatch` instead of `globby`
- [x] `log` as function `{ "action": "copy", "from": "...",  "to": "..." }`
- [ ] Update benchmark
- [ ] Automation benchmark

**Comment by mrmlnc** [comment]
Automation benchmark

**Comment by mrmlnc** [comment]
Benchmark with:

  * previous version of Syncy
  * grunt-sync
  * gulp-directory-sync
  * cpx
